-- MySQL Script generated by MySQL Workbench
-- 06/05/15 23:00:19
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ictcloud
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ictcloud
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ictcloud` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `ictcloud` ;

-- -----------------------------------------------------
-- Table `ictcloud`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ictcloud`.`User` (
  `IdUser` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `IdRole` TINYINT(1) NOT NULL,
  `FullName` VARCHAR(100) NOT NULL,
  `UserName` VARCHAR(16) NOT NULL,
  `PassWord` CHAR(32) NOT NULL,
  `Email` VARCHAR(255) NULL,
  `DiskQuota` BIGINT(20) NOT NULL,
  `DiskUsed` BIGINT(20) NOT NULL DEFAULT 0,
  `Status` INT(1) NOT NULL,
  PRIMARY KEY (`IdUser`),
  UNIQUE INDEX `username_UNIQUE` (`UserName` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ictcloud`.`Group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ictcloud`.`Group` (
  `IdGroup` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `GroupName` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`IdGroup`),
  UNIQUE INDEX `groupname_UNIQUE` (`GroupName` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ictcloud`.`UserGroup`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ictcloud`.`UserGroup` (
  `IdUser` INT(11) UNSIGNED NOT NULL,
  `IdGroup` INT(11) UNSIGNED NOT NULL,
  `StatusAdmin` BIT(1) NOT NULL,
  PRIMARY KEY (`IdUser`, `IdGroup`, `StatusAdmin`),
  INDEX `fk_UserGroup_Group1_idx` (`IdGroup` ASC),
  CONSTRAINT `fk_UserGroup_User1`
    FOREIGN KEY (`IdUser`)
    REFERENCES `ictcloud`.`User` (`IdUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UserGroup_Group1`
    FOREIGN KEY (`IdGroup`)
    REFERENCES `ictcloud`.`Group` (`IdGroup`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'users_has_groups';


-- -----------------------------------------------------
-- Table `ictcloud`.`FileType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ictcloud`.`FileType` (
  `IdFileType` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `MimeType` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`IdFileType`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ictcloud`.`File`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ictcloud`.`File` (
  `IdFile` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `IdUser` INT(11) UNSIGNED NOT NULL,
  `IdFileType` INT(11) UNSIGNED NOT NULL,
  `IdFolder` INT(11) UNSIGNED NULL,
  `FileName` VARCHAR(255) NOT NULL,
  `FileSize` INT(11) NOT NULL,
  `LastAccessed` INT(11) NOT NULL,
  `LastModified` INT(11) NOT NULL,
  PRIMARY KEY (`IdFile`),
  INDEX `fk_File_User1_idx` (`IdUser` ASC),
  INDEX `fk_File_FileType1_idx` (`IdFileType` ASC),
  INDEX `fk_File_File1_idx` (`IdFolder` ASC),
  CONSTRAINT `fk_File_User1`
    FOREIGN KEY (`IdUser`)
    REFERENCES `ictcloud`.`User` (`IdUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_File_FileType1`
    FOREIGN KEY (`IdFileType`)
    REFERENCES `ictcloud`.`FileType` (`IdFileType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_File_File1`
    FOREIGN KEY (`IdFolder`)
    REFERENCES `ictcloud`.`File` (`IdFile`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ictcloud`.`Share`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ictcloud`.`Share` (
  `IdFile` INT(11) UNSIGNED NOT NULL,
  `IdUser` INT(11) UNSIGNED NOT NULL,
  `FullName` VARCHAR(255) NOT NULL,
  `Privilege` TINYINT(5) NULL,
  PRIMARY KEY (`IdFile`, `IdUser`),
  INDEX `fk_File_has_User_User1_idx` (`IdUser` ASC),
  INDEX `fk_File_has_User_File1_idx` (`IdFile` ASC),
  CONSTRAINT `fk_File_has_User_File1`
    FOREIGN KEY (`IdFile`)
    REFERENCES `ictcloud`.`File` (`IdFile`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_File_has_User_User1`
    FOREIGN KEY (`IdUser`)
    REFERENCES `ictcloud`.`User` (`IdUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ictcloud`.`ChatMessage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ictcloud`.`ChatMessage` (
  `IdChatMessage` INT(11) UNSIGNED NOT NULL,
  `IdSender` INT(11) UNSIGNED NOT NULL,
  `IdReceiver` INT(11) UNSIGNED NOT NULL,
  `TextMessage` TEXT NOT NULL,
  `Time` INT(11) NOT NULL,
  `SenderName` VARCHAR(100) NOT NULL,
  `ReceiverName` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`IdChatMessage`),
  INDEX `fk_ChatMessage_User1_idx` (`IdSender` ASC),
  INDEX `fk_ChatMessage_User2_idx` (`IdReceiver` ASC),
  CONSTRAINT `fk_ChatMessage_User1`
    FOREIGN KEY (`IdSender`)
    REFERENCES `ictcloud`.`User` (`IdUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ChatMessage_User2`
    FOREIGN KEY (`IdReceiver`)
    REFERENCES `ictcloud`.`User` (`IdUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ictcloud`.`Task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ictcloud`.`Task` (
  `IdTask` INT(11) UNSIGNED NOT NULL,
  `IdUser` INT(11) UNSIGNED NOT NULL,
  `TaskName` VARCHAR(255) NOT NULL,
  `Description` VARCHAR(255) NULL,
  `TimeCreated` INT(11) NOT NULL,
  `TimeToExecute` INT(11) NOT NULL,
  `ExecuteType` VARCHAR(20) NULL,
  PRIMARY KEY (`IdTask`),
  INDEX `fk_Task_User1_idx` (`IdUser` ASC),
  CONSTRAINT `fk_Task_User1`
    FOREIGN KEY (`IdUser`)
    REFERENCES `ictcloud`.`User` (`IdUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ictcloud`.`TaskUser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ictcloud`.`TaskUser` (
  `IdTask` INT(11) UNSIGNED NOT NULL,
  `IdUser` INT(11) UNSIGNED NOT NULL,
  `TimeExecuted` INT(11) NULL,
  PRIMARY KEY (`IdTask`, `IdUser`),
  INDEX `fk_TaskUser_User1_idx` (`IdUser` ASC),
  CONSTRAINT `fk_TaskUser_Task1`
    FOREIGN KEY (`IdTask`)
    REFERENCES `ictcloud`.`Task` (`IdTask`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TaskUser_User1`
    FOREIGN KEY (`IdUser`)
    REFERENCES `ictcloud`.`User` (`IdUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ictcloud`.`Contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ictcloud`.`Contact` (
  `IdUser` INT(11) UNSIGNED NOT NULL,
  `IdContactUser` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`IdUser`, `IdContactUser`),
  INDEX `fk_Contact_User2_idx` (`IdContactUser` ASC),
  CONSTRAINT `fk_Contact_User1`
    FOREIGN KEY (`IdUser`)
    REFERENCES `ictcloud`.`User` (`IdUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contact_User2`
    FOREIGN KEY (`IdContactUser`)
    REFERENCES `ictcloud`.`User` (`IdUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ictcloud`.`NotificationType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ictcloud`.`NotificationType` (
  `IdNotificationType` INT(11) UNSIGNED NOT NULL,
  `Name` VARCHAR(255) NULL,
  PRIMARY KEY (`IdNotificationType`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ictcloud`.`UserNotification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ictcloud`.`UserNotification` (
  `IdUserNotification` INT(11) UNSIGNED NOT NULL,
  `IdUser` INT(11) UNSIGNED NOT NULL,
  `IdNotificationType` INT(11) UNSIGNED NOT NULL,
  `Description` VARCHAR(255) NULL,
  `TimeExpires` INT(11) NULL,
  INDEX `fk_UserNotification_User1_idx` (`IdUser` ASC),
  INDEX `fk_UserNotification_NotificationType1_idx` (`IdNotificationType` ASC),
  PRIMARY KEY (`IdUserNotification`),
  CONSTRAINT `fk_UserNotification_User1`
    FOREIGN KEY (`IdUser`)
    REFERENCES `ictcloud`.`User` (`IdUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UserNotification_NotificationType1`
    FOREIGN KEY (`IdNotificationType`)
    REFERENCES `ictcloud`.`NotificationType` (`IdNotificationType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ictcloud`.`UserLog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ictcloud`.`UserLog` (
  `IdUserLog` INT(11) UNSIGNED NOT NULL,
  `IdUser` INT(11) UNSIGNED NOT NULL,
  `LoggedIn` INT(11) NOT NULL,
  `LoggedOut` INT(11) NULL,
  PRIMARY KEY (`IdUserLog`),
  INDEX `fk_UserLog_User1_idx` (`IdUser` ASC),
  CONSTRAINT `fk_UserLog_User1`
    FOREIGN KEY (`IdUser`)
    REFERENCES `ictcloud`.`User` (`IdUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ictcloud`.`UserTracking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ictcloud`.`UserTracking` (
  `IdUserLog` INT(11) UNSIGNED NOT NULL,
  `EventDetails` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`IdUserLog`),
  CONSTRAINT `fk_UserTracking_UserLog1`
    FOREIGN KEY (`IdUserLog`)
    REFERENCES `ictcloud`.`UserLog` (`IdUserLog`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ictcloud`.`DatabaseConf`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ictcloud`.`DatabaseConf` (
  `DbKey` VARCHAR(255) NOT NULL,
  `DbValue` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`DbKey`, `DbValue`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ictcloud`.`CloudConf`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ictcloud`.`CloudConf` (
  `CloudKey` VARCHAR(255) NOT NULL,
  `CloudValue` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`CloudKey`, `CloudValue`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
